name:                pandoc-changes
version:             0.1.0.0
github:              "dbalseiro/pandoc-changes"
license:             BSD3
author:              "Diego Balseiro"
maintainer:          "dbalseiro@stackbuilders.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dbalseiro/pandoc-changes#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  pandoc-changes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-changes

